### ISSUE TITLE
Add CIMDraw to LF Energy landscape page?

### ISSUE THREAD

**Issue by nicorikken** [danielePala/CIMDraw#11]
For the LFEnergy there is a [landscape page](https://landscape.lfenergy.org/) that maps software projects in an high-level architecture. More on this technical architecture is available on the [website](https://www.lfenergy.org/projects/functional-architecture/) or in this video recording of the [Technical Architecture Workshop in 2020](https://youtu.be/FLhWR_HefZo?t=190). Of course the LFEnergy are represented here, but also other software projects that exist in the same category, both open source or proprietary software.

CIMDraw is not on this landscape page, despite being interesting for the sector and other CIM tools being listed. I think it makes sense to add CIMDraw there. I'm happy to make a pull-request to the [landschape git repository](https://github.com/lf-energy/lfenergy-landscape) but decided to first come here to discuss it with you.

I was thinking of adding the following data to the [landscape.yml](https://github.com/lf-energy/lfenergy-landscape/blob/main/landscape.yml) file, under the section **Shared > Data Management**:
```yaml
          - item:
            name: CIMDraw
            description:  CIMDraw is a WebApp to view IEC CIM (CGMES) files
            homepage_url: https://danielepala.github.io/CIMDraw/
            repo_url: https://danielepala.github.io/CIMDraw/
            logo: none # Is there a logo?
            twitter: # none I guess?
            crunchbase: https://www.crunchbase.com/organization/ricerca-sul-sistema-energetico-rse-s-p-a
```

What do you think of this idea and details? Would you like to file the PR yourself, or should I do it?
